# Generated by Django 5.2.12 on 2026-03-26 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_local', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_predio', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=50, unique=True)),
                ('capacidade', models.DecimalField(decimal_places=0, max_digits=10)),
                ('unidade_medida', models.CharField(max_length=20)),
                ('valor_bem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('situacao', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_manutencao.categoria')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_manutencao.local')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_manutencao.marca')),
            ],
        ),
        migrations.AddField(
            model_name='local',
            name='predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_manutencao.predio'),
        ),
    ]
